### ISSUE TITLE
ACL parsing broken w 0.14.0?

### ISSUE THREAD

**Issue by mrosack** [hyperledger/composer-vscode-plugin#47]
Does a new version of this just need to be compiled and released against the 0.14.0 schema?  I'm getting validation errors against the new rules needed for the NetworkAdmin in 0.14.0.  Thanks!

**Comment by m-g-k** [comment]
Yes, you are correct, I will do this tomorrow. Thanks for the report!

**Comment by m-g-k** [comment]
This is now fixed in the latest release (0.14.1).
