### ISSUE TITLE
Better visualization of relationships in UML diagrams

### ISSUE THREAD

**Issue by bjrnt** [hyperledger/composer-vscode-plugin#88]
Hello,

With only the default options enables, the PlantUML output shows inheritance (e.g. `AddCar` inherits from `Transaction`, `Car` inherits from `Vehicle`) and so on. Would there be any interest in adding more information and relationships to these diagrams? 

I've hacked on my own version of the extension to add additional information for relationships and concepts inside transactions, assets, etc. My goal has been to get a better image of the relationships of the various entities in use within the blockchain.

As a tiny example, the following CTO file:
```
namespace org.example

transaction AddCar {
  o String model
  o String year
}

transaction RemoveCar {
  --> Car car
}

asset Vehicle identified by registration {
  o String registration
}

asset Car extends Vehicle {
  o String model
  o String year
}
```
might be visualized to include the relationship from `RemoveCar --> Car` as
![screen shot 2018-10-30 at 6 51 10 pm](https://user-images.githubusercontent.com/484114/47709997-f9cbcc00-dc74-11e8-85ab-ec9a38d0bb18.png)

Is this something you would be interested in merging into the extension? I realize that since the way things are visualized might often be up to individual preference, it might be difficult to find something that can fit all users, but I'd be glad to discuss this further if there is interest.

**Comment by dselman** [comment]
Nice!

**Comment by if1999615** [comment]
Would love to see this developed.
